---
- name: setup justus
  hosts: web_servers
  tasks: #    - name: copy file to server
    #      copy:
    #        src: ../JustUs/tsconfig.json
    #        dest: ~/

    - name: clone repo
      git:
        repo: https://github.com/jojothomas1515/JustUs
        clone: yes
        dest: ~/JustUs
        update: yes

    - name: install psycopg2 dependency
      become: yes
      apt:
        name: libpq-dev
        state: present

    - name: install postgresql
      become: yes
      apt:
        name: postgresql
        state: present

    - name: install requirements
      become: yes
      pip:
        requirements: /home/ubuntu/JustUs/requirements.txt
        state: present
