---
- name: setup justus
  hosts: web_servers
  tasks: #    - name: copy file to server
    #      copy:
    #        src: ../JustUs/tsconfig.json
    #        dest: ~/

    - name: clone repo
      git:
        repo: https://github.com/jojothomas1515/JustUs
        clone: yes
        dest: ~/JustUs
        update: yes

    - name: install psycopg2 dependency
      become: yes
      apt:
        name: libpq-dev
        state: present

    - name: install postgresql
      become: yes
      apt:
        name: postgresql
        state: present

    - name: start postgresql
      become: yes
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: execute sql script
      become: yes
      shell: sudo -upostgres psql -f /home/ubuntu/JustUs/sql/setup_database.sql

    - name: install requirements
      become: yes
      pip:
        requirements: /home/ubuntu/JustUs/requirements.txt
        state: present

    - name: copy justus nginx conf
      become: yes
      copy:
        src: /home/ubuntu/JustUs/justus_nginx.conf
        remote_src: true
        dest: /etc/nginx/sites-available/justus_nginx.conf
        owner: root
        group: root
        mode: 0644

    - name: enable justus nginx conf
      become: yes
      file:
        state: link
        src: /etc/nginx/sites-available/justus_nginx.conf
        dest: /etc/nginx/sites-enabled/justus_nginx.conf

    - name: unlink default nginx conf
      become: yes
      file:
        state: absent
        path: /etc/nginx/sites-enabled/default

    - name: restart nginx
      become: yes
      service:
        name: nginx
        state: restarted

    - name: justus gunicorn service
      become: yes
      template:
          src: /home/ubuntu/JustUs/justus.service
          remote_src: yes
          dest: /etc/systemd/system/justus

    - name: justus gunicorn service
      become: yes
      copy:
          src: /home/ubuntu/JustUs/justus.service
          remote_src: yes
          dest: /etc/systemd/system/justus.service
          owner: root
          group: root
          mode: 0644

    - name: start justus gunicorn service
      become: yes
      service:
        name: justus
        state: started
        enabled: yes